SCIPIONPYTHON = "SCIPIONPYTHON"
PROTID = 'PROTID'
SESSIONFILE = "SESSIONFILE"
CHIMERA_MAP_TEMPLATE_FILE_NAME = 'CHIMERA_MAP_TEMPLATE_FILE_NAME'
CHIMERA_PDB_TEMPLATE_FILE_NAME = 'CHIMERA_PDB_TEMPLATE_FILE_NAME'